### ISSUE TITLE
ANSI code being printed to terminal when using alacritty

### ISSUE THREAD

**Issue by donbex** [kdheepak/taskwarrior-tui#46]
In edit mode `taskwarrior-tui` crashes after exiting the editor, whether there are changes or not.

**Steps to reproduce the behaviour:**

- Create empty `taskrc` and database:
```
$ mkdir tasktmp
$ touch tmprc
```

- Create a test task:
```
$ TASKRC=tmprc TASKDATA=tasktmp task add test
```

- Start `taskwarrior-tui`:
```
$ TASKRC=tmprc TASKDATA=tasktmp taskwarrior-tui
```
- Select the _test_ task and open the editor with `e`

- Quit the editor

_Output:_
```
Launching '/usr/bin/nvim "task.131964a7.task"' now...
Editing complete.
No edits were detected.
TASKRC override: /home/bexie/tmprc
TASKDATA override: /home/bexie/tasktmp
[taskwarrior-tui error]: Failed to create a Task from JSON. Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui
```

_Note:_
Setting `RUST_BACKTRACE=1` does not produce any additional output.

**Environment:**

- Operating System: Arch Linux
- Installation: `taskwarrior-tui` package from the AUR
- taskwarrior-tui version: 0.9.3

- task version: 2.5.1

**Comment by kdheepak** [comment]
Interestingly I'm not able to reproduce this. Does this happen when only one task is defined? I followed your exact steps and everything worked as expected. I'm on a MacOS.

**Comment by kdheepak** [comment]
I'm not able to reproduce on a Ubuntu machine as well.

![taskeditubuntu mov](https://user-images.githubusercontent.com/1813121/98343254-cb54fa00-1fce-11eb-9307-64505f8a1169.gif)

Any change it could have to do with your neovim configuration? Can you try using a blank `.vimrc` and see if that makes a difference?

**Comment by donbex** [comment]
Well, colour me puzzled... I cannot reproduce this issue with _nano_, _emacs_ or _vim_, either. However, the issue is still present when setting `editor=nvim -u NONE` in _tmprc_. Could you test with _neovim_ as well?

_Note:_ `-u NONE` prevents _neovim_ from loading any configuration files, including plugins.

**Comment by kdheepak** [comment]
I use neovim on my machine, and I don't have any issue. Can you run `task edit` from your command line and see if neovim works in that case. Because that is essentially what `taskwarrior-tui` does.

**Comment by donbex** [comment]
`task edit` works without issues.

**Comment by kdheepak** [comment]
Can you run `task export` and paste the results here? Does `task export` differ at all when editing using emacs / vim / nano versus when editing with neovim?

My guess is that after editing your task, something weird is going on and taskwarrior-tui is not able to import the exported output of taskwarrior. It is so surprising that it happens only with neovim.

If you are able to build from source and add some `dbg!(variable_name)` in one of these functions, we can figure out what is going on fairly quickly

https://github.com/kdheepak/taskwarrior-tui/blob/fa9095aedd5855f4c7a465cc9b4eb83e976cf7cb/src/app.rs#L638-L644

https://github.com/kdheepak/taskwarrior-tui/blob/fa9095aedd5855f4c7a465cc9b4eb83e976cf7cb/src/app.rs#L810-L844

Unfortunately, since I'm not able to reproduce locally, I'm not sure how to help debug this issue.

**Comment by kdheepak** [comment]
Any luck?

**Comment by donbex** [comment]
Sorry, I have been busy and couldn't get around to this until now. Unfortunately, the output of `task export` does not differ at all when opening the test task with either nano or neovim.

I am happy to apply any patches and compile from source, but I am not sure as to where you would like me to put those debug statements. Could you give me a patch instead?

**Comment by donbex** [comment]
So, I tried adding the `dbg!` instructions you asked for, but when I try to compile I get errors like this

```
error[E0382]: borrow of moved value: `task`
   --> src/app.rs:877:21
    |
856 |         let mut task = Command::new("task");
    |             -------- move occurs because `task` has type `std::process::Command`, which does not implement the `Copy` trait
...
862 |         dbg!(task);
    |         ----------- value moved here
...
877 |                     task.arg(&s);
    |                     ^^^^ value borrowed here after move
```

Unfortunately, I am not familiar with rust and I have no clue how to work around this...

**Comment by kdheepak** [comment]
Thanks that is super helpful! Would it be possible for you to send me your `taskrc` file? Is it not empty? Why is your filter this string `0000/0000`?

**Comment by kdheepak** [comment]
```
[src/app.rs:862] &task = "task" "rc.json.array=on" "rc.confirmation=off" "export"
[src/app.rs:871] &filter = "status:pending 0000/0000"
[src/app.rs:875] &cmd = [
    "status:pending",
    "0000/0000",
]
[src/app.rs:886] &output = Output {
    status: ExitStatus(
        ExitStatus(
            512,
        ),
    ),
    stdout: "",
    stderr: "TASKRC override: /home/donbex/taskdebug/tmprc\nTASKDATA override: /home/donbex/taskdebug/tasktmp\nConfiguration override rc.json.array:on\nConfiguration override rc.confirmation:off\nCannot divide Boolean values\n",
}
[src/app.rs:888] &data = ""
[src/app.rs:890] &error = "TASKRC override: /home/donbex/taskdebug/tmprc\nTASKDATA override: /home/donbex/taskdebug/tasktmp\nConfiguration override rc.json.array:on\nConfiguration override rc.confirmation:off\nCannot divide Boolean values\n"
```

This is basically the problem. `taskwarrior` doesn't understand what that `0000/0000` means. Do you happen to know where it is coming from?

![Screen Shot 2020-11-16 at 2 00 44 PM](https://user-images.githubusercontent.com/1813121/99307705-216a3e80-2814-11eb-88f9-9c0745ebcb95.png)

**Comment by donbex** [comment]
> Thanks that is super helpful! Would it be possible for you to send me your `taskrc` file? Is it not empty?

The `taskrc` is empty.

> Why is your filter this string `0000/0000`?

Not a clue. The filter line appears only as `status:pending` in `taskwarrior-tui`. I don't know why editing the task with `neovim` might introduce that...

**Comment by donbex** [comment]
I am afraid this might have something to do with `alacritty`, since the issue does not seem to appear with `kitty`. What terminal emulator are you using, and would you be able to see if you can reproduce the issue with [`alacritty`](https://github.com/alacritty/alacritty)?

**Comment by martinzh** [comment]
It is not related with `alacritty`, I have the same issue on MacOS with iTerm and NeoVim

**Comment by kdheepak** [comment]
Can you share the error message after it crashes?

**Comment by martinzh** [comment]
`Launching 'nvim "task.0601240e.task"' now...
Editing complete.
Edits were detected.
Description modified.
[taskwarrior-tui error]: Failed to create a Task from JSON. Please report as a github issue on https://github.com/kdheepak/taskwarrior-tui`

**Comment by kdheepak** [comment]
Can you run `task export` and share the results?

**Comment by martinzh** [comment]
This is the output from `task export`:
```
[
{"id":1,"description":"Figura comportamiento temporal","due":"20210118T200000Z","entry":"20210112T014158Z","modified":"20210112T041233Z","project":"Coy:JohnSabina","status":"pending","tags":["DataVis","Coyuntura","TlateLAB","Test"],"uuid":"f24e95fb-b203-460f-997b-62738755cf54","urgency":8.01848},
{"id":2,"description":"Modificar vis redes","due":"20210118T200000Z","entry":"20210112T014422Z","modified":"20210112T033254Z","project":"Coy:JohnSabina","status":"pending","tags":["DataVis","Coyuntura","TlateLAB"],"uuid":"720cee60-9046-4086-9c42-f8ac75cd0086","urgency":8.01848},
{"id":3,"description":"Modificar vis de RT de RTs","due":"20210118T200000Z","entry":"20210112T014927Z","modified":"20210112T033325Z","project":"Coy:JohnSabina","status":"pending","tags":["DataVis","TlateLAB"],"uuid":"8613049c-5425-4ca2-b8fd-aa1c5e679064","urgency":7.91848},
{"id":4,"description":"Modificar análisis de cuentas como el de tendencias","due":"20210118T200000Z","entry":"20210112T014955Z","modified":"20210112T035657Z","project":"Coy:JohnSabina","status":"pending","tags":["Code","Twitter","TlateLAB"],"uuid":"6d6a0adb-a05c-4a5a-a245-464386e0862f","urgency":8.01848},
{"id":5,"description":"Test otro otro","entry":"20210112T035707Z","modified":"20210112T151928Z","status":"pending","tags":["personal"],"uuid":"0601240e-884b-41c9-9682-94d7658eaeb6","urgency":0.8},
{"id":0,"description":"Test","end":"20210112T033446Z","entry":"20210112T033425Z","modified":"20210112T033446Z","status":"deleted","tags":["SportsAnalytics"],"uuid":"8a6e38cc-f5f0-4992-8e1f-a4ca9d28683e","urgency":0.8},
{"id":0,"description":"Hacer figura de geometría de ABP","end":"20210111T211843Z","entry":"20200424T173242Z","modified":"20210111T211843Z","project":"Tesis","reviewed":"20200428T044435Z","status":"deleted","uuid":"3c9046da-e43b-48ac-ad41-8a57663c7653","urgency":2.4411},
{"id":0,"description":"Hacer figura trayectorias de ABP","end":"20210111T211844Z","entry":"20200424T192657Z","modified":"20210111T211844Z","project":"Tesis","reviewed":"20200428T044438Z","status":"deleted","uuid":"302aecf9-5b62-4e81-8cae-c18de8cb1596","urgency":2.43562},
{"id":0,"description":"Calcular MSD para PBA","end":"20210111T211845Z","entry":"20200424T202750Z","modified":"20210111T211845Z","project":"Tesis","reviewed":"20200428T044447Z","status":"deleted","uuid":"facca1de-1df1-471c-91e5-81ecc59d530f","annotations":[{"entry":"20200424T202806Z","description":"Caclucos analiticos"},{"entry":"20200424T202836Z","description":"Ver Bechinger1602 para referencias"}],"urgency":3.33562},
{"id":0,"description":"Revisar referencias calculos MSD en Bechinger","end":"20210111T211846Z","entry":"20200424T204406Z","modified":"20210111T211846Z","project":"Tesis","reviewed":"20200428T044451Z","status":"deleted","uuid":"412a85bd-f8ec-4210-96ee-d821b483d5ce","urgency":2.43562},
{"id":0,"description":"Revisar scripts que usé en la pres19","end":"20210111T211847Z","entry":"20200519T165354Z","modified":"20210111T211847Z","project":"EFOS20","status":"deleted","uuid":"5fd00e32-1195-4f3d-92cf-024bbdadb6e9","urgency":2.30411},
{"id":0,"description":"Actualizar scripts redes y otros anteriores","end":"20210111T211848Z","entry":"20200519T165412Z","modified":"20210111T211848Z","project":"EFOS20","status":"deleted","uuid":"146e36ad-cb96-4872-bbae-67a22179b7f3","urgency":2.30411},
{"id":0,"description":"Comparar info categórica de la DB de EFOS con la de categorica","end":"20210111T211910Z","entry":"20200519T165446Z","modified":"20210111T211910Z","project":"EFOS20","status":"deleted","uuid":"3536eca7-67b2-43ef-978f-12612a4f0888","urgency":2.30411},
{"id":0,"description":"Revisar referencias motifs","end":"20210111T211849Z","entry":"20200519T165529Z","modified":"20210111T211849Z","project":"EFOS20","status":"deleted","uuid":"a21ad3f8-ec18-40cb-aca2-d780f429dca2","urgency":2.30411},
{"id":0,"description":"Decidir que info categórica usar para caracterizar enlaces","end":"20210111T211850Z","entry":"20200519T165634Z","modified":"20210111T211850Z","project":"EFOS20","status":"deleted","uuid":"8e6202d8-5488-4666-af4c-255a05d318f4","urgency":2.30411},
{"id":0,"description":"Calcular MSD de reactivos","end":"20210111T211851Z","entry":"20200528T225345Z","modified":"20210111T211851Z","project":"Patchy","status":"deleted","uuid":"f6f77450-8c94-4c67-a571-f7007719fb9b","urgency":2.24932},
{"id":0,"description":"Calcular coeficiente de difusión","end":"20210111T211853Z","entry":"20200528T225408Z","modified":"20210111T211853Z","project":"Patchy","status":"deleted","uuid":"5f902bd7-138b-42aa-97a6-1ff4f0613159","urgency":2.24932},
{"id":0,"description":"Visualizar MSD","end":"20210111T211858Z","entry":"20200528T225417Z","modified":"20210111T211858Z","project":"Patchy","status":"deleted","uuid":"08fdc28f-248c-4c44-a87d-6226e6cb5102","urgency":2.24932},
{"id":0,"description":"Generar archivo de info categórica para los sospechosos del proyecto anterior","end":"20210111T211901Z","entry":"20200629T183235Z","modified":"20210111T211901Z","project":"EFOS20","status":"deleted","uuid":"04d51671-f23b-4af7-8f1d-4b6e8f2097a7","urgency":2.07397},
{"id":0,"description":"Solicitar lista actualizada de RFCA genéricos","end":"20210111T211903Z","entry":"20200629T191247Z","modified":"20210111T211903Z","project":"EFOS20","status":"deleted","uuid":"5c69967c-2c01-4ca5-bb7c-2f0bfe187fa1","urgency":2.07397},
{"id":0,"description":"Hacer listas de EFOS artificiales","end":"20210111T211904Z","entry":"20200707T004234Z","modified":"20210111T211904Z","project":"EFOS20","status":"deleted","uuid":"081c105a-21ad-4981-a8ce-7a62ac593708","urgency":2.03562},
{"id":0,"description":"Construir redes entre RFCA con EFOS artificiales","end":"20210111T211905Z","entry":"20200707T004234Z","modified":"20210111T211905Z","project":"EFOS20","status":"deleted","uuid":"b8f91091-3d53-4455-aee1-ae28fcb2a076","urgency":2.03562},
{"id":0,"description":"Construir redes entre categóricas con EFOS artificiales","end":"20210111T211907Z","entry":"20200707T004234Z","modified":"20210111T211907Z","project":"EFOS20","status":"deleted","uuid":"1fc608df-6611-4e00-a836-c5aaa294a108","urgency":2.03562},
{"id":0,"depends":"1fc608df-6611-4e00-a836-c5aaa294a108,081c105a-21ad-4981-a8ce-7a62ac593708,b8f91091-3d53-4455-aee1-ae28fcb2a076","description":"Construir redes de \"modelo nulo\"","end":"20210111T211912Z","entry":"20200707T004234Z","modified":"20210111T211912Z","project":"EFOS20","status":"deleted","uuid":"f52bb46a-bc1f-417b-99ef-ddc2b9019e2c","urgency":2.03562},
{"id":0,"description":"Hacer JuliaDB con info categórica","end":"20200727T180416Z","entry":"20200519T165330Z","modified":"20200727T180416Z","project":"EFOS20","status":"completed","uuid":"92dfcad7-6bd9-4c71-9439-cfdcedaa147b","annotations":[{"entry":"20200630T190031Z","description":"Prueba nota"}],"urgency":3.10411},
{"id":0,"description":"Arreglar posiciones de figuras","end":"20200720T192715Z","entry":"20200720T192434Z","modified":"20200720T192717Z","project":"EFOS20","status":"deleted","uuid":"9728a852-6015-414b-96f7-9cf06fa64c46","urgency":1.9589},
{"id":0,"description":"Arreglar posiciones de figuras","end":"20200720T192700Z","entry":"20200720T192422Z","modified":"20200720T192702Z","project":"EFOS20","status":"deleted","uuid":"307cf0f3-a509-4dc3-8749-af9ce812aa23","urgency":1.9589},
{"id":0,"description":"Arreglar posiciones de figuras","end":"20200720T192652Z","entry":"20200720T192408Z","modified":"20200720T192655Z","project":"EFOS20","status":"deleted","uuid":"339eb16c-caa4-4be8-9961-93a3f226c3ee","urgency":1.9589},
{"id":0,"description":"Arreglar posiciones de figuras","end":"20200720T192631Z","entry":"20200720T192405Z","modified":"20200720T192634Z","project":"EFOS20","status":"deleted","uuid":"ea779bad-4850-46a1-8f54-d0d61b05c55b","urgency":1.9589},
{"id":0,"description":"Avanzar sección ASM","end":"20200720T191318Z","entry":"20200424T171518Z","modified":"20200720T191318Z","project":"Tesis","reviewed":"20200428T044504Z","status":"completed","uuid":"74a92f9f-5fba-467f-b863-22d64c91de4f","urgency":2.4411},
{"id":0,"description":"Generar visualizaciones de noProds","end":"20200707T184043Z","entry":"20200707T012611Z","modified":"20200707T184043Z","project":"Patchy","status":"completed","uuid":"d705a7cd-2780-4ce2-ac27-9d799934d1a4","urgency":2.03562},
{"id":0,"description":"Incluir opción para seleccionar prod o no prod","end":"20200707T184035Z","entry":"20200707T012611Z","modified":"20200707T184035Z","project":"Patchy","status":"completed","uuid":"60c85b57-cdf5-4a3a-b1b2-feafbb951087","urgency":2.03562},
{"id":0,"description":"Revisar documento efecto carrusel","end":"20200706T231703Z","entry":"20200519T165548Z","modified":"20200706T231703Z","project":"EFOS20","status":"completed","uuid":"5a39de71-8921-4589-8408-d3729abdf6fe","urgency":2.30411},
{"id":0,"description":"Hacer diccionarions con nombres y claves de categóricas","end":"20200706T231648Z","entry":"20200704T032639Z","modified":"20200706T231648Z","project":"EFOS20","status":"completed","uuid":"62a4116d-1156-4787-a7d6-2a5e3fcfdb8a","urgency":2.05205},
{"id":0,"description":"Hacer script para generar archivo \"headless\" de info categórica","end":"20200706T231632Z","entry":"20200630T005955Z","modified":"20200706T231632Z","project":"EFOS20","status":"completed","uuid":"21d4f7eb-8201-4613-8ec5-9a3203c95d05","urgency":2.07397},
{"id":0,"description":"Separar generar imágenes para comparar enlaces de generar las listas de enlaces","end":"20200706T231249Z","entry":"20200630T014446Z","modified":"20200706T231249Z","project":"EFOS20","status":"completed","uuid":"1c61b344-4364-47df-acf1-ecc62e124cd9","urgency":2.07397},
{"id":0,"description":"Agregar año y mes como parámetros de entrada a scripts","end":"20200630T185323Z","entry":"20200630T014146Z","modified":"20200630T185323Z","project":"EFOS20","status":"completed","uuid":"44f75eec-1e47-4269-bcfd-5e9d7e20cccd","urgency":2.07397},
{"id":0,"description":"Script para generar snapshots","end":"20200605T195244Z","entry":"20200528T225331Z","modified":"20200605T195244Z","project":"Patchy","status":"completed","uuid":"dad235ad-c1e7-49e4-b8a5-afe1f3dfccfb","urgency":2.24932},
{"id":0,"description":"Figuras REP","end":"20200529T234934Z","entry":"20200503T022846Z","modified":"20200529T234934Z","project":"Patchy","status":"completed","uuid":"036a09bb-5163-4db3-b977-3fe9173816f1","urgency":2.39178},
{"id":0,"description":"Script para extraer estado final de sims","end":"20200529T234838Z","entry":"20200528T225319Z","modified":"20200529T234838Z","project":"Patchy","status":"completed","uuid":"515b5412-cfae-457a-b2a6-7726dd0d5c15","urgency":2.24932},
{"id":0,"description":"Calcular distribuciones de actividades de RFCA desconocidos","end":"20200528T223059Z","entry":"20200528T170741Z","modified":"20200528T223059Z","project":"EFOS20","status":"completed","uuid":"c252d274-1774-465f-b768-e3e7029bf002","urgency":2.25479},
{"id":0,"description":"Hacer figuras de distribuciones de info categórica de EFOS","end":"20200528T223038Z","entry":"20200519T165515Z","modified":"20200528T223038Z","project":"EFOS20","status":"completed","uuid":"0d71dac0-937e-4685-b956-b05c81e068e7","urgency":2.30411},
{"id":0,"description":"Figuras ATT","end":"20200505T013253Z","entry":"20200503T022851Z","modified":"20200505T013253Z","project":"Patchy","status":"completed","uuid":"7e0edcff-ac3c-4d29-bc0a-c6b3b92eee6d","urgency":2.39178},
{"id":0,"description":"Figuras ACT","end":"20200504T221337Z","entry":"20200503T022854Z","modified":"20200504T221337Z","project":"Patchy","status":"completed","uuid":"d4f30abf-d7b8-44cd-b9fe-1f8cb3dd9128","urgency":2.39178},
{"id":0,"description":"Subir código al repositorio","end":"20200427T182736Z","entry":"20200427T164725Z","modified":"20200427T182736Z","project":"NetCovid","status":"completed","uuid":"2ca9d4ba-065e-4710-82f1-b6a8de36fa53","urgency":2.42466},
{"id":0,"description":"Terminar script sims_LFR","end":"20200427T182730Z","entry":"20200427T164658Z","modified":"20200427T182730Z","project":"NetCovid","status":"completed","uuid":"d3e7a3fc-446f-46b3-a536-93650f46c664","urgency":2.42466},
{"id":0,"description":"Revisar implementación lockdown","end":"20200427T182722Z","entry":"20200427T164603Z","modified":"20200427T182722Z","project":"NetCovid","status":"completed","uuid":"4aabe853-5eaa-49d7-bee3-1f65d86eaa13","urgency":2.42466},
{"id":0,"description":"Subir figuras al Drive","end":"20200423T185941Z","entry":"20200422T180719Z","modified":"20200423T185941Z","project":"NetCovid","status":"completed","uuid":"9b7521c1-3060-4c6e-b43a-c1847d84160b","urgency":2.44658},
{"id":0,"description":"Implementar distanciamiento en el modelo","end":"20200422T202904Z","entry":"20200422T180758Z","modified":"20200422T202904Z","project":"NetCovid","status":"completed","uuid":"56238761-5ae0-4315-98e1-8b95264c026f","urgency":2.44658},
{"id":0,"description":"Generar figuras de distribuciones","end":"20200422T202847Z","entry":"20200422T180706Z","modified":"20200422T202847Z","project":"NetCovid","status":"completed","uuid":"fbc46f70-2cb6-4f8f-950c-68412ed3f2de","urgency":2.44658},
{"id":0,"description":"PomodoroLog","end":"20200422T180819Z","entry":"20200422T180819Z","modified":"20200422T205417Z","status":"completed","uuid":"1f02077a-1656-4200-9fd7-318b7482ea4f","annotations":[{"entry":"20200422T192131Z","description":"Pomodoro uuid:fbc46f70-2cb6-4f8f-950c-68412ed3f2de"},{"entry":"20200422T205417Z","description":"Pomodoro uuid:9b7521c1-3060-4c6e-b43a-c1847d84160b"}],"urgency":2.34658},
{"id":0,"description":"PomodoroLog","end":"20200424T171522Z","entry":"20200424T171522Z","modified":"20200424T203929Z","status":"completed","uuid":"bac7134f-d833-4274-87f6-5a9e2d1ac4f1","annotations":[{"entry":"20200424T174023Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200424T193917Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200424T200422Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200424T203929Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"}],"urgency":2.4411},
{"id":0,"description":"PomodoroLog","end":"20200427T164928Z","entry":"20200427T164928Z","modified":"20200428T002823Z","status":"completed","uuid":"e0ba9238-6edf-4344-8dec-759b78dbe10f","annotations":[{"entry":"20200427T171428Z","description":"Pomodoro uuid:4aabe853-5eaa-49d7-bee3-1f65d86eaa13"},{"entry":"20200427T181609Z","description":"Pomodoro uuid:4aabe853-5eaa-49d7-bee3-1f65d86eaa13"},{"entry":"20200427T233108Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200428T000012Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200428T002823Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"}],"urgency":2.42466},
{"id":0,"description":"PomodoroLog","end":"20200504T170838Z","entry":"20200504T170838Z","modified":"20200504T232123Z","status":"completed","uuid":"bc96433c-9ab7-47a4-8efa-fb40e6c0fba7","annotations":[{"entry":"20200504T173339Z","description":"Pomodoro uuid:d4f30abf-d7b8-44cd-b9fe-1f8cb3dd9128"},{"entry":"20200504T183102Z","description":"Pomodoro uuid:d4f30abf-d7b8-44cd-b9fe-1f8cb3dd9128"},{"entry":"20200504T185605Z","description":"Pomodoro uuid:d4f30abf-d7b8-44cd-b9fe-1f8cb3dd9128"},{"entry":"20200504T192120Z","description":"Pomodoro uuid:d4f30abf-d7b8-44cd-b9fe-1f8cb3dd9128"},{"entry":"20200504T215113Z","description":"Pomodoro uuid:d4f30abf-d7b8-44cd-b9fe-1f8cb3dd9128"},{"entry":"20200504T223849Z","description":"Pomodoro uuid:7e0edcff-ac3c-4d29-bc0a-c6b3b92eee6d"},{"entry":"20200504T232123Z","description":"Pomodoro uuid:7e0edcff-ac3c-4d29-bc0a-c6b3b92eee6d"}],"urgency":2.3863},
{"id":0,"description":"PomodoroLog","end":"20200511T181206Z","entry":"20200511T181206Z","modified":"20200511T210045Z","status":"completed","uuid":"5585d281-2e82-418f-931d-f01a6237ce7c","annotations":[{"entry":"20200511T183707Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200511T190210Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200511T210045Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"}],"urgency":2.34247},
{"id":0,"description":"PomodoroLog","end":"20200519T173643Z","entry":"20200519T173643Z","modified":"20200519T182718Z","status":"completed","uuid":"98e0c3a0-dc0a-44e4-9173-3e51e65732a0","annotations":[{"entry":"20200519T180144Z","description":"Pomodoro uuid:92dfcad7-6bd9-4c71-9439-cfdcedaa147b"},{"entry":"20200519T182718Z","description":"Pomodoro uuid:92dfcad7-6bd9-4c71-9439-cfdcedaa147b"}],"urgency":2.20411},
{"id":0,"description":"PomodoroLog","end":"20200525T173706Z","entry":"20200525T173706Z","modified":"20200525T180207Z","status":"completed","uuid":"8d05f912-d079-4cf2-adb3-cff4ad92e656","annotations":[{"entry":"20200525T180207Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"}],"urgency":2.07123},
{"id":0,"description":"PomodoroLog","end":"20200528T172334Z","entry":"20200528T172334Z","modified":"20200528T222249Z","status":"completed","uuid":"f69bcc72-63fe-47bd-a97b-f103fd46c7cb","annotations":[{"entry":"20200528T174834Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"},{"entry":"20200528T181338Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"},{"entry":"20200528T184506Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"},{"entry":"20200528T191009Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"},{"entry":"20200528T195338Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"},{"entry":"20200528T211213Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"},{"entry":"20200528T214446Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"},{"entry":"20200528T222249Z","description":"Pomodoro uuid:c252d274-1774-465f-b768-e3e7029bf002"}],"urgency":2.25479},
{"id":0,"description":"PomodoroLog","end":"20200529T162938Z","entry":"20200529T162938Z","modified":"20200529T231329Z","status":"completed","uuid":"a722ad27-9561-433b-b4d4-e3a584f04fa2","annotations":[{"entry":"20200529T165438Z","description":"Pomodoro uuid:515b5412-cfae-457a-b2a6-7726dd0d5c15"},{"entry":"20200529T172143Z","description":"Pomodoro uuid:515b5412-cfae-457a-b2a6-7726dd0d5c15"},{"entry":"20200529T174648Z","description":"Pomodoro uuid:515b5412-cfae-457a-b2a6-7726dd0d5c15"},{"entry":"20200529T181153Z","description":"Pomodoro uuid:515b5412-cfae-457a-b2a6-7726dd0d5c15"},{"entry":"20200529T221112Z","description":"Pomodoro uuid:515b5412-cfae-457a-b2a6-7726dd0d5c15"},{"entry":"20200529T223637Z","description":"Pomodoro uuid:515b5412-cfae-457a-b2a6-7726dd0d5c15"},{"entry":"20200529T231329Z","description":"Pomodoro uuid:515b5412-cfae-457a-b2a6-7726dd0d5c15"}],"urgency":2.24932},
{"id":0,"description":"PomodoroLog","end":"20200602T180117Z","entry":"20200602T180117Z","modified":"20200602T182617Z","status":"completed","uuid":"65bc5a69-17df-4a7f-b9fd-059056463af4","annotations":[{"entry":"20200602T182617Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"}],"urgency":2.02192},
{"id":0,"description":"PomodoroLog","end":"20200630T180855Z","entry":"20200630T180855Z","modified":"20200630T183355Z","status":"completed","uuid":"76cf3914-4f15-442b-af4f-2b0e346c2787","annotations":[{"entry":"20200630T183355Z","description":"Pomodoro uuid:44f75eec-1e47-4269-bcfd-5e9d7e20cccd"}],"urgency":1.86849},
{"id":0,"description":"PomodoroLog","end":"20200720T160046Z","entry":"20200720T160046Z","modified":"20200720T181225Z","status":"completed","uuid":"3a81cdad-b39e-4558-991e-9f3e460b7472","annotations":[{"entry":"20200720T162547Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200720T165600Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200720T174620Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"},{"entry":"20200720T181225Z","description":"Pomodoro uuid:74a92f9f-5fba-467f-b863-22d64c91de4f"}],"urgency":1.96438},
{"id":0,"description":"PomodoroLog","end":"20200727T180502Z","entry":"20200727T180502Z","modified":"20200727T215349Z","status":"completed","uuid":"5a4a433a-48f1-4d0e-b4e9-a22e2153a435","annotations":[{"entry":"20200727T183003Z","description":"Pomodoro uuid:3536eca7-67b2-43ef-978f-12612a4f0888"},{"entry":"20200727T215349Z","description":"Pomodoro uuid:3536eca7-67b2-43ef-978f-12612a4f0888"}],"urgency":1.82055},
{"id":0,"description":"PomodoroLog","end":"20200728T172947Z","entry":"20200728T172947Z","modified":"20200728T182335Z","status":"completed","uuid":"26cafa00-a4d4-44c7-99be-7310f8485017","annotations":[{"entry":"20200728T175447Z","description":"Pomodoro uuid:3536eca7-67b2-43ef-978f-12612a4f0888"},{"entry":"20200728T182335Z","description":"Pomodoro uuid:3536eca7-67b2-43ef-978f-12612a4f0888"}],"urgency":1.82055},
{"id":0,"description":"PomodoroLog","end":"20200819T162543Z","entry":"20200819T162543Z","modified":"20200819T175452Z","status":"completed","uuid":"9d140f93-45d6-46c9-b176-312402019aea","annotations":[{"entry":"20200819T165044Z","description":"Pomodoro uuid:f52bb46a-bc1f-417b-99ef-ddc2b9019e2c"},{"entry":"20200819T175452Z","description":"Pomodoro uuid:f52bb46a-bc1f-417b-99ef-ddc2b9019e2c"}],"urgency":1.7},
{"id":0,"description":"PomodoroLog","end":"20201013T155547Z","entry":"20201013T155547Z","modified":"20201013T190952Z","status":"completed","uuid":"41e78a09-320c-462c-979b-5da95d3cd514","annotations":[{"entry":"20201013T162047Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"},{"entry":"20201013T165259Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"},{"entry":"20201013T172701Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"},{"entry":"20201013T181519Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"},{"entry":"20201013T184028Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"},{"entry":"20201013T190952Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"}],"urgency":1.49863},
{"id":0,"description":"PomodoroLog","end":"20201116T152023Z","entry":"20201116T152023Z","modified":"20201116T154523Z","status":"completed","uuid":"efba461c-577d-4a21-8a61-2a27953870bb","annotations":[{"entry":"20201116T154523Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"}],"urgency":1.11233},
{"id":0,"description":"PomodoroLog","end":"20201209T154556Z","entry":"20201209T154556Z","modified":"20201209T161056Z","status":"completed","uuid":"7dd5c997-2fb5-4d41-a0e2-742d43e0cc4a","annotations":[{"entry":"20201209T161056Z","description":"Pomodoro uuid:3c9046da-e43b-48ac-ad41-8a57663c7653"}],"urgency":0.986301},
{"id":0,"description":"PomodoroLog","end":"20210112T014807Z","entry":"20210112T014807Z","modified":"20210112T014807Z","status":"completed","uuid":"650f0276-bb1c-45d8-9e77-d73b1d713148","urgency":0}
]
```

**Comment by kdheepak** [comment]
I imported all your tasks and was able to edit them without any issues. Can you tell me which task causes a crash?

**Comment by kdheepak** [comment]
@donbex @martinzh, can you run the latest taskwarrior-tui and see if it crashes. I've added better stacktraces now and it should be easier to figure out what the problem might be when the stacktrace is printed.

**Comment by donbex** [comment]
I pulled and built the latest commit at the time of writing (tagged v0.9.12), but for some reason I am not getting any debug trace. Here's a gif of the issue:
![taskwarrior-tui](https://user-images.githubusercontent.com/894255/107279315-ca5cba00-6a4e-11eb-8cf4-65a902a699fc.gif)

**Comment by kdheepak** [comment]
Sorry I missed this, why are you trying to type `0000/0000`? 

<img width="500" alt="Screen Shot 2021-02-08 at 1 59 12 PM" src="https://user-images.githubusercontent.com/1813121/107280643-d4ae9200-6a15-11eb-828e-5c6b66f7459d.png">

taskwarrior doesn't support using `/` in the filter string I don't think.

**Comment by donbex** [comment]
I'm not. It appears by itself as soon as the editor exits.

Also, for some reason the issue appears harder to reproduce under X11 (xmonad), while under Wayland (sway) it is consistent.

**Comment by kdheepak** [comment]
Oh I see. It's automatically entering `0000/0000`. That is so odd. 

It must have something to do with these lines:

https://github.com/kdheepak/taskwarrior-tui/blob/5e469b8a6d164c14822de54087f4d6a7858fa877/src/app.rs#L1369-L1371

I'm not having this issue in my environments though. Are you able to hit backspace immediately after hitting `:wq` and deleting `0000/0000`?

Also, if you are interested in debugging further, I would play around with the sleep timings in `utils.rs`. For example like this one:

https://github.com/kdheepak/taskwarrior-tui/blob/5e469b8a6d164c14822de54087f4d6a7858fa877/src/util.rs#L81

There's only 4 instances of `thread::sleep`. If you can increase the timings and see if that helps, that'll be useful information.

**Comment by donbex** [comment]
> I'm not having this issue in my environments though. Are you able to hit backspace immediately after hitting `:wq` and deleting `0000/0000`?

Yes, if I'm quick enough I am able to delete the `0000/0000` string, preventing the crash.

> There's only 4 instances of `thread::sleep`. If you can increase the timings and see if that helps, that'll be useful information.

The only instance that seems to have any effect on the issue is the first one, at line 81: increasing the time argument delays the appearance of the `0000/0000` string.

**Comment by kdheepak** [comment]
But it always appears regardless of the size of the delay? I might have to share this question with some neovim devs to see if they might be able to share insight as to what is going on. It could very well be a neovim related issue.

**Comment by donbex** [comment]
The largest value I tried is 10s, i.e. `thread::sleep(Duration::from_millis(10000))`, but it still appears.

**Comment by kdheepak** [comment]
Can you run the following rust file:

```
// tmp.rs

use std::process::Command;

pub fn main() {
    let task_id = 1;
    let r = Command::new("task").arg(format!("{}", task_id)).arg("edit").spawn();

    let child = r.unwrap();
    let output = child.wait_with_output().unwrap();
    if !output.status.success() {
        dbg!(format!(
            "`task edit` for task `{}` failed. {}{}",
            task_id,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        ));
    }
}
```

And after you edit the task and save it, see if it still prints `0000/0000` to the terminal.

You can run it using the following:

```
cargo install single
cargo single run tmp.rs
```

If you use `cargo single` I'll be able to add dependencies to this file and build up to a MWE for reproducible the problem.

**Comment by donbex** [comment]
```
$ cargo single run tmp.rs
error: failed to parse manifest at `/home/bexie/code/ttui-test/tmp/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  expected an equals, found a newline at line 10 column 7
```
I'm not sure what's going on here... the `Cargo.toml` file was automatically generated, line 10 is the last one, but it only has 6 columns:
```
[package]
name = "tmp"
version = "0.1.0"
authors = [ ... ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tmp.rs
```

P.S.: It appears that the package is called `cargo-single`.

**Comment by kdheepak** [comment]
> P.S.: It appears that the crate is called cargo-single.

My bad.

> Edit: Never mind... I copied your snippet as-is, but apparently cargo single uses the comments at the beginning of a file to list its dependencies.

Oops! My bad again! I should have mentioned that.

**Comment by mkobel** [comment]
I'm not sure if it is related: I once set an invalid parent (ID instead of UUID), this caused taskwarrior-tui to crash with the same error message. I manually edited the data files to get rid of the invalid parent to resolve the issue.

**Comment by donbex** [comment]
As it turns out, the `println!` macro does its own formatting and was throwing an error. After changing lines 10 and 15
```
println!(
    "`task edit` for task `{}` failed. {}{}",
    task_id,
    String::from_utf8_lossy(&output.stdout),
    String::from_utf8_lossy(&output.stderr),
);
```
the snippet ran. However, the edit was successful and the debugging string wasn't triggered.

**Comment by kdheepak** [comment]
Can you try the following when you are available?

```
// tui = { version = "0.12", optional = true, default-features = false }
// crossterm = { version = "0.17", optional = true, default-features = false }

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]

use std::process::Command;

use crossterm::{
    event::{self, DisableMouseCapture, EnableMouseCapture},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen, Clear, ClearType},
    cursor,
};
use tui::{backend::CrosstermBackend, Terminal};

use std::io::{self, Write};
use std::sync::{Arc, Mutex};
use std::{sync::mpsc, thread, time::Duration};

#[derive(Debug, Clone, Copy)]
pub enum Key {
    Backspace,
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    PageUp,
    PageDown,
    BackTab,
    Delete,
    Insert,
    F(u8),
    Char(char),
    Alt(char),
    Ctrl(char),
    Null,
    Esc,
}

#[derive(Debug, Clone, Copy)]
pub struct EventConfig {
    pub tick_rate: Duration,
}

#[derive(Debug, Clone, Copy)]
pub enum Event<I> {
    Input(I),
    Tick,
}

pub fn setup_terminal() -> Terminal<CrosstermBackend<io::Stdout>> {
    enable_raw_mode().unwrap();
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen).unwrap();
    execute!(stdout, Clear(ClearType::All)).unwrap();
    let backend = CrosstermBackend::new(stdout);
    Terminal::new(backend).unwrap()
}

pub fn destruct_terminal() {
    disable_raw_mode().unwrap();
    execute!(io::stdout(), LeaveAlternateScreen, DisableMouseCapture).unwrap();
    execute!(io::stdout(), cursor::Show).unwrap();
}

pub struct Events {
    pub rx: mpsc::Receiver<Event<Key>>,
    pub tx: mpsc::Sender<Event<Key>>,
    pub pause_stdin: Arc<Mutex<bool>>,
    pub pause_ticker: Arc<Mutex<bool>>,
}

impl Events {
    pub fn with_config(config: EventConfig) -> Events {
        use crossterm::event::{KeyCode::*, KeyModifiers};
        let (tx, rx) = mpsc::channel();
        let pause_stdin = Arc::new(Mutex::new(false));
        let pause_ticker = Arc::new(Mutex::new(false));
        let _input_handle = {
            let tx = tx.clone();
            let pause_stdin = pause_stdin.clone();
            thread::spawn(move || {
                loop {
                    if *pause_stdin.lock().unwrap() {
                        thread::sleep(Duration::from_millis(250));
                        continue;
                    }
                    // poll for tick rate duration, if no event, sent tick event.
                    if let event::Event::Key(key) = event::read().unwrap() {
                        let key = match key.code {
                            Backspace => Key::Backspace,
                            Enter => Key::Char('\n'),
                            Left => Key::Left,
                            Right => Key::Right,
                            Up => Key::Up,
                            Down => Key::Down,
                            Home => Key::Home,
                            End => Key::End,
                            PageUp => Key::PageUp,
                            PageDown => Key::PageDown,
                            Tab => Key::Char('\t'),
                            BackTab => Key::BackTab,
                            Delete => Key::Delete,
                            Insert => Key::Insert,
                            F(k) => Key::F(k),
                            Null => Key::Null,
                            Esc => Key::Esc,
                            Char(c) => match key.modifiers {
                                KeyModifiers::NONE | KeyModifiers::SHIFT => Key::Char(c),
                                KeyModifiers::CONTROL => Key::Ctrl(c),
                                KeyModifiers::ALT => Key::Alt(c),
                                _ => Key::Null,
                            },
                        };
                        tx.send(Event::Input(key)).unwrap();
                    }
                }
            })
        };
        let _tick_handle = {
            let tx = tx.clone();
            let pause_ticker = pause_ticker.clone();
            thread::spawn(move || loop {
                // print!("\r\n");
                // dbg!(*pause_ticker.lock().unwrap());
                while *pause_ticker.lock().unwrap() {
                    thread::sleep(Duration::from_millis(250));
                }
                if tx.send(Event::Tick).is_err() {
                    break;
                }
                thread::sleep(config.tick_rate);
            })
        };

        Events { rx, tx, pause_stdin, pause_ticker }
    }

    /// Attempts to read an event.
    /// This function will block the current thread.
    pub fn next(&self) -> Result<Event<Key>, mpsc::RecvError> {
        self.rx.recv()
    }

    pub fn pause_ticker(&self) {
        *self.pause_ticker.lock().unwrap() = true;
        // print!("\r\n");
        // dbg!(*self.pause_ticker.lock().unwrap());
    }

    pub fn resume_ticker(&self) {
        *self.pause_ticker.lock().unwrap() = false;
    }

    pub fn pause_event_loop(&self) {
        *self.pause_stdin.lock().unwrap() = true;
    }

    pub fn resume_event_loop(&self) {
        *self.pause_stdin.lock().unwrap() = false;
    }

    pub fn pause_key_capture(&self, terminal: &mut Terminal<CrosstermBackend<io::Stdout>>) {
        self.pause_event_loop();
        std::thread::sleep(std::time::Duration::from_millis(50));
        disable_raw_mode().unwrap();
        execute!(io::stdout(), LeaveAlternateScreen, DisableMouseCapture).unwrap();
        terminal.show_cursor().unwrap();
    }

    pub fn resume_key_capture(&self, terminal: &mut Terminal<CrosstermBackend<io::Stdout>>) {
        enable_raw_mode().unwrap();
        execute!(io::stdout(), EnterAlternateScreen, EnableMouseCapture).unwrap();
        std::thread::sleep(std::time::Duration::from_millis(50));
        self.resume_event_loop();
        terminal.resize(terminal.size().unwrap()).unwrap();
    }
}


fn task_edit(task_id: usize) {
    let r = Command::new("task").arg(format!("{}", task_id)).arg("edit").spawn();

    let child = r.unwrap();
    let output = child.wait_with_output().unwrap();
    if !output.status.success() {
        println!(
            "`task edit` for task `{}` failed. {}{}",
            task_id,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}

fn main() {
    let task_id = 1;

    // Terminal initialization
    let mut terminal = setup_terminal();
    // Setup event handlers
    let events = Events::with_config(EventConfig {
        tick_rate: Duration::from_millis(1000),
    });
    events.pause_key_capture(&mut terminal);

    std::thread::sleep(std::time::Duration::from_millis(500));
    task_edit(task_id);
    std::thread::sleep(std::time::Duration::from_millis(500));

    events.resume_key_capture(&mut terminal);

    destruct_terminal();

}
```

You'll have to edit the `Cargo.toml` file to add the following

```
[features]
default = ["crossterm-backend"]
crossterm-backend = ["tui/crossterm", "crossterm"]
```

**Comment by kdheepak** [comment]
@mkobel I think your issue was different from the one @donbex is having.

**Comment by kdheepak** [comment]
@donbex I changed it such that it doesn't crash immediately on an invalid filter. See https://github.com/kdheepak/taskwarrior-tui/issues/77.

I tested it by typing 0000/0000 manually and it doesn't crash. This doesn't resolve the underlying issue, but I think it'll make using taskwarrior-tui slightly less annoying for you? You'll have to manually backspace to remove the `0000/0000` after you finish modifying a task.

**Comment by donbex** [comment]
Thanks @kdheepak, this sounds like a good workaround.

**Comment by kdheepak** [comment]
I think it'd still be nice to figure out why neovim is printing `0000/0000`, and report that to the neovim developers.

**Comment by kdheepak** [comment]
Were you able to run [the code snippet above](https://github.com/kdheepak/taskwarrior-tui/issues/46#issuecomment-775573598)?

**Comment by donbex** [comment]
I finished working late today and didn't try yet, sorry. I'll see if I can try it tomorrow.

**Comment by kdheepak** [comment]
No worries! Whenever you get the chance :)

**Comment by kdheepak** [comment]
If you try the latest master, I think it might solve the 0000/0000 with neovim. It so, I'll make a new release.

**Comment by donbex** [comment]
Sorry, it took me longer than I expected to get back to you.

> Can you try the following when you are available?

What should be the output of this? At the moment the only output I get is the same as `task edit`:
```
$ TASKRC=tmprc TASKDATA=tasktmp cargo single run ~/code/ttui-test/ttui-test.rs
Launching '/usr/bin/nvim "task.86b0d194.task"' now...
Editing complete.
No edits were detected.
TASKRC override: /home/bexie/taskdebug/tmprc
TASKDATA override: /home/bexie/taskdebug/tasktmp
```

> If you try the latest master, I think it might solve the `0000/0000` with neovim. If so, I'll make a new release.

Unfortunately the `0000/0000` is still there, but at least now it doesn't crash ttui. Thanks for the workaround!

**Comment by kdheepak** [comment]
> Unfortunately the 0000/0000 is still there, but at least now it doesn't crash ttui. Thanks for the workaround!

That's unfortunate. I was getting the `0000/0000` occasionally after I made a change but then after I made some fixes I wasn't any more. I thought that'd fix it for you as well but it appears it has not. I have an idea that I can try but that'd going to take a while for me to implement.

**Comment by donbex** [comment]
Out of curiosity I tried to taskwarrior-tui version 0.9.8. There are only a couple of occurrences of `0000/0000`, all but one generated as part of the crash. The odd one out is from a process forked by the main taskwarrior-tui process (pid 14993):
```
read(0, "\33]11;rgb:0000/0000/0000\7", 1204) = 24
```
Unfortunately I have trouble understanding exactly what this process is and, most importantly, what's feeding into its stdin, but from what I can tell this looks like part of an ANSI colour code. At the moment I have no clue where this might be coming from. 🤔

**Comment by kdheepak** [comment]
When `taskwarrior-tui` runs `task edit` it is done as a subprocess: 

https://github.com/kdheepak/taskwarrior-tui/blob/62c9e2f02cb7893ebf051ee07c5248723c559e9d/src/app.rs#L1236-L1269

`task edit` in turn launches another subprocess:

https://github.com/GothenburgBitFactory/taskwarrior/blob/098be0747d150dec8207502ec4bfebf38ce805bc/src/commands/CmdEdit.cpp#L789

Before `taskwarrior-tui` launches `task edit` though, it stops reading key presses, and after `task edit` is complete, it resumes reading key presses:

https://github.com/kdheepak/taskwarrior-tui/blob/62c9e2f02cb7893ebf051ee07c5248723c559e9d/src/app.rs#L1452-L1454

However, this pause and resume is implemented as a `AtomicBool` (equivalent of using a `Mutex` on a `Bool`):

https://github.com/kdheepak/taskwarrior-tui/blob/fa0d76a8b2b89381124b57a050d0779b75c9f9c6/src/util.rs#L170-L175

This is the key capture thread that the `AtomicBool` (`pause_stdin`) pauses by using a sleep:

https://github.com/kdheepak/taskwarrior-tui/blob/fa0d76a8b2b89381124b57a050d0779b75c9f9c6/src/util.rs#L79-L115

---

All of this is to say, the way it is currently implemented, there might be maximum of 250 milliseconds delay between when `task edit` is completed and when `taskwarrior-tui` continues to consume the key presses again:

https://github.com/kdheepak/taskwarrior-tui/blob/fa0d76a8b2b89381124b57a050d0779b75c9f9c6/src/util.rs#L82

You can try decreasing this sleep delay of `250` on line 82 to see if that changes the behavior for you.

Any suggestions to better implement this are welcome.

I think when I rewrite this section of the code, I'll use channels. And I'm hoping that will solve the problem.

It is still so surprising that this only happens for your configuration, and only with neovim.

**Comment by kdheepak** [comment]
Also, this `\33]11;rgb:0000/0000/0000\7` does look like an escape code. I'm surprised by this `\33]` though. Usually it is `\33[`. 

This is purely speculation, this might be a terminal emulator specific sequence emitted by neovim that is trying to read the foreground / background color of the terminal. 

Also, what shell are you using? Have you tried using an alternate shell (bash, zsh, fish) etc? If you are using zsh, do you have prompts set up? Just curious if that could affect this?

**Comment by kdheepak** [comment]
I finally got around to installing alacritty! I was able to reproduce the issue, and I think I was able to resolve it partially. Sorry it took so long. I made some changes in the referenced PR, and now in my testing it about 30 times or so I only got a random string being automatically entered in the filter box just once. I might be able to tweak it further but it'll longer to start up `task edit`. Also, I don't get `0000/0000`, I get `2bf3/2bf3` or something else like that. So it might be possible I fixed a different issue and you are still encountering the same thing.

Let me know if you still experience this in the latest master, and we can exchange alacritty configurations to debug further. Thanks for sticking with the issue and responding all this while!

**Comment by donbex** [comment]
According to the [list of xTerm's escape sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands) `\33]11;rgb:0000/0000/0000\7` is indeed an ANSI code and it means "set terminal background to black". A little experimenting shows that the colour in the command is indeed the background colour from Alacritty's configuration, which explains why you get a different string.

With the current master the issue is present only some of the time, so I would hazard that there is probably some race condition at play here.

**Comment by kdheepak** [comment]
Thanks for figuring that out! That is very useful information. So it is definitely something taskwarrior-tui is doing incorrectly.

**Comment by kdheepak** [comment]
I added a flush before calling `task edit`, and that seems to have done the trick. It'd be great if you can test it and see if you still see the issue some of the time. I'm not able to replicate it any more.

**Comment by donbex** [comment]
Unfortunately, the issue is still present for me.

**Comment by kdheepak** [comment]
Yeah, I was able to replicate it once again. After the most recent PR though, where I added in a sleep again, I am not able to reproduce it. Can you try it again?

**Comment by donbex** [comment]
Still there, although now it appears to happen only about 2/3 of the time (from a not-really-statistically-significant sample of 10 tries).

**Comment by kdheepak** [comment]
That's so strange. I don't have it happen any more. I'm using the default alacritty configuration with no changes. Would you be able to share your `~/.config/alacritty/alacritty.yml` file?

**Comment by kdheepak** [comment]
It's be great if you can try `cargo run` and `cargo run --release` to see if there's any differences there.

**Comment by donbex** [comment]
> It's be great if you can try `cargo run` and `cargo run --release` to see if there's any differences there.

I didn't notice any difference, unfortunately.


> That's so strange. I don't have it happen any more. I'm using the default alacritty configuration with no changes. Would you be able to share your `~/.config/alacritty/alacritty.yml` file?

Sure, [here it is](https://github.com/kdheepak/taskwarrior-tui/files/5984241/alacritty.yml.tar.gz). There is very little different from the default, aside from a custom font and a few colours schemes (the currently active one is called `default`).

**Comment by kdheepak** [comment]
Hmm. I tried the color section from your file and no luck. It works fine for me. 

I know you tried this before, but can you try increasing this delay again and see if you still encounter this issue?

https://github.com/kdheepak/taskwarrior-tui/blob/c8ecf55bb4897f1bcb86c04f69fb258468482314/src/util.rs#L148

https://github.com/kdheepak/taskwarrior-tui/blob/c8ecf55bb4897f1bcb86c04f69fb258468482314/src/util.rs#L158

**Comment by kdheepak** [comment]
I've tried everything I could think of and I'm not sure how to proceed on this. With alacritty and `vi` I'm getting odd behavior as well (it doesn't print `0000/0000` but it modifies the task list or opens the context menu when I hit `e`). My hunch, although weak, is telling me that this has more to do with alacritty than nvim / vim / vi.

**Comment by kdheepak** [comment]
I've made a Minimal Working Example (MWE) of this bug. I'm able to get similar behavior with vi, vim and neovim but not with nano. Here's a gif of it in action.

![taskwarrior-tui-bug](https://user-images.githubusercontent.com/1813121/108163475-53599e00-70ac-11eb-91b8-e8e508eeb547.gif)

This is troubling because in the current implementation I'm interpreting those to be user entered key strokes, which means the ANSI codes that are being printed may cause arbitrary changes to the users task list.

I'm not able to reproduce this if I remove the "threading" related pieces in my code, and when everything reactive to what the user does it works as intended. I don't understand why this is the case, but that is good news in a way, since it means this can potentially be solved with fixes on my end (I think).

I wanted to warn you about this. I don't want this program to cause intended issues with your taskwarrior setup. Maybe avoid using the `e` key for now.

The code to reproduce the issue is below. I'll post on the crossterm repo to see if they can suggest something.

```rust
use crossterm::{
    event,
    terminal::{disable_raw_mode, enable_raw_mode},
};
use std::error::Error;
use std::process::Command;
use std::result::Result;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::{sync::mpsc, thread, time::Duration, time::Instant};

#[derive(Debug, Clone, Copy)]
pub enum Key {
    Char(char),
    Null,
}

#[derive(Debug, Clone, Copy)]
pub struct EventConfig {
    pub tick_rate: Duration,
}

#[derive(Debug, Clone, Copy)]
pub enum Event<I> {
    Input(I),
    Tick,
}

pub struct Events {
    pub rx: mpsc::Receiver<Event<Key>>,
    pub tx: mpsc::Sender<Event<Key>>,
    pub pause_stdin: Arc<AtomicBool>,
}

impl Events {
    #[cfg(feature = "crossterm")]
    pub fn with_config(config: EventConfig) -> Events {
        use crossterm::event::{KeyCode::*};
        let (tx, rx) = mpsc::channel();
        let pause_stdin = Arc::new(AtomicBool::new(false));
        let tick_rate = config.tick_rate;
        let _input_handle = {
            let tx = tx.clone();
            let pause_stdin = pause_stdin.clone();
            thread::spawn(move || {
                let mut last_tick = Instant::now();
                loop {
                    let timeout = tick_rate
                        .checked_sub(last_tick.elapsed())
                        .unwrap_or_else(|| Duration::from_secs(0));

                    if pause_stdin.load(Ordering::SeqCst) {
                        thread::sleep(Duration::from_millis(250));
                        continue;
                    }

                    if event::poll(timeout).unwrap() {
                        if let event::Event::Key(key) = event::read().unwrap() {
                            let key = match key.code {
                                Char(c) => Key::Char(c),
                                _ => Key::Null,
                            };
                            tx.send(Event::Input(key)).unwrap();
                        }
                    }

                    if last_tick.elapsed() >= tick_rate && tx.send(Event::Tick).is_ok() {
                        last_tick = Instant::now();
                    }
                }
            })
        };
        Events { rx, tx, pause_stdin }
    }

    /// Attempts to read an event.
    /// This function will block the current thread.
    pub fn next(&self) -> Result<Event<Key>, mpsc::RecvError> {
        self.rx.recv()
    }

    pub fn pause_event_loop(&self) {
        self.pause_stdin.swap(true, Ordering::SeqCst);
    }

    pub fn resume_event_loop(&self) {
        self.pause_stdin.swap(false, Ordering::SeqCst);
    }

    pub fn pause_key_capture(&self) {
        self.pause_event_loop();
        disable_raw_mode().unwrap();
    }

    pub fn resume_key_capture(&self) {
        enable_raw_mode().unwrap();
        self.resume_event_loop();
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    // Terminal initialization
    enable_raw_mode().unwrap();

    let mut i = 0;

    // Setup event handlers
    let events = Events::with_config(EventConfig {
        tick_rate: Duration::from_millis(1000),
    });

    loop {
        match events.next()? {
            Event::Input(input) => {
                match input {
                    Key::Char('q') => break,
                    Key::Char('e') => {
                        events.pause_key_capture();
                        let r = Command::new("vi").spawn();
                        match r {
                            Ok(child) => {
                                let output = child.wait_with_output();
                                match output {
                                    Ok(output) => {
                                        if !output.status.success() {
                                            Err(format!(
                                                "process status was not success. {}{}",
                                                String::from_utf8_lossy(&output.stdout),
                                                String::from_utf8_lossy(&output.stderr),
                                            ))
                                        } else {
                                            String::from_utf8_lossy(&output.stdout);
                                            String::from_utf8_lossy(&output.stderr);
                                            Ok(())
                                        }
                                    }
                                    Err(err) => Err(format!("Failed to get output of process: {}", err)),
                                }
                            }
                            Err(err) => Err(format!("Failed to spawn process: {}", err)),
                        }?;
                        events.resume_key_capture();
                    },
                    Key::Char(c) => {
                        disable_raw_mode().unwrap();
                        println!("{}", c);
                        enable_raw_mode().unwrap();
                    },
                    _ => (),
                };
            }
            Event::Tick => {
                disable_raw_mode().unwrap();
                println!("Tick: {}", i);
                enable_raw_mode().unwrap();
                i += 1;
            }
        };
    }
    disable_raw_mode().unwrap();
    Ok(())
}
```

**Comment by kdheepak** [comment]
Interestingly I get similar codes in iTerm2 as I do in Alacritty.

<img width="1440" alt="Screen Shot 2021-02-16 at 11 24 44 PM" src="https://user-images.githubusercontent.com/1813121/108164557-3de57380-70ae-11eb-99d5-da4c92226829.png">

<img width="1440" alt="Screen Shot 2021-02-16 at 11 24 54 PM" src="https://user-images.githubusercontent.com/1813121/108164560-3e7e0a00-70ae-11eb-848e-33b9af4e2012.png">

**Comment by kdheepak** [comment]
After lots of experimenting and debugging _I think_ I've fixed this. I'm no longer able to get ansi codes being printed to `taskwarrior-tui` or in the `MWE` when using `alacritty` / `iTerm2` and when shelling out to `vi`, `vim` and `nvim` on my Mac. It'd be great if you can give it go to check if that is the case for you as well.

**Comment by kdheepak** [comment]
You can try it out in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.10.4

**Comment by donbex** [comment]
Thanks for the hard work you've put into this. I'll try out the new changes as soon as I have some time today or tomorrow.

My guess as for why you don't see those keycodes after running `nano` is that it doesn't allow theming, so it doesn't have to reset the terminal colours after exiting. I expect you'd see the same keycodes after running other themable TUI applications, like `mc`.

**Comment by donbex** [comment]
I tried the latest commit (0ae677f) and it was much better, although I cannot say that the issue is completely resolved: in 3 out of 40 tests the issue was still present, i.e. the string `0000/0000` appeared in the filter field after editing a task.

**Comment by kdheepak** [comment]
Thanks for trying it!

Can you change these lines:

https://github.com/kdheepak/taskwarrior-tui/blob/0ae677fbaa76ac52d6ff7af49d0ee2bdebe53fed/src/util.rs#L90-L92

to the following:

```rust
                    let timeout = Duration::from_millis(10)
                        .checked_sub(last_tick.elapsed())
                        .unwrap_or_else(|| Duration::from_millis(0));
```


and try again? If I set the timeout too low (i.e. `0` milliseconds), then the CPU consumption goes up to like 50% when monitoring using htop. Setting it too high causes the issue.

If using `0` solves the problem for you, I'll make it a configurable option.

**Comment by donbex** [comment]
Indeed, setting the timeout to 0ms drove the CPU usage way too high. However, setting it to 5ms seemed to solve the issue (out of 100 tests) and also kept the CPU usage to reasonable levels. Thanks again!
```
let timeout = Duration::from_millis(10)
    .checked_sub(last_tick.elapsed())
    .unwrap_or_else(|| Duration::from_millis(5));
```

**Comment by kdheepak** [comment]
I think I can change it to the above timings. The CPU usage seems reasonable. Thanks for testing.

**Comment by kdheepak** [comment]
Did you test a 100 times or so manually? Or did you test programmatically. It would be good to add such a test into the test suite so there isn't a regression in the future.

**Comment by donbex** [comment]
Unfortunately I did it manually. I assume it would be possible to set up an automated "puppeted" test, but that would be pretty fragile and I wouldn't recommend keeping it long term for regression testing. It should be possible to write a dummy program to use in place of an editor that changes the terminal colours (assuming that's enough to trigger a colour reset via the OSC 11 code) and immediately exits. I still wouldn't know how to check that taskwarrior-tui isn't reading part of the OSC code as input — mainly because I don't know the codebase (nor Rust, for that matter), but I presume it could be relatively straightforward to do in a unit test.

**Comment by kdheepak** [comment]
wow thanks for being so dedicated :) And thanks for the input, I'll look into how to set up a test for this.

**Comment by kdheepak** [comment]
I made a new release that has the fix for this issue: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.11.0.

**Comment by kdheepak** [comment]
I re-did the event handler using `async` and you can try it on the latest commit on `master` at the moment. I think it is much faster and nicer to use :) 

And now there's no sleeps and delays any more like I had before to avoid the ANSI codes being printed. I didn't test on linux but in my testing on my mac using alacritty and iterm2 I never had ANSI codes being printed to the terminal even once. Hopefully there's no regression here but if you do notice anything please comment here / open a new issue!

**Comment by kdheepak** [comment]
You can try it out in this release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.0.
